admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/myspace  
    requirements:
        _locale: '%allowedLanguages%'
    
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/user  
    requirements:
        _locale: '%allowedLanguages%'
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}  
    requirements:
        _locale: '%allowedLanguages%'

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile  
    requirements:
        _locale: '%allowedLanguages%'

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register  
    requirements:
        _locale: '%allowedLanguages%'

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting  
    requirements:
        _locale: '%allowedLanguages%'

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile  
    requirements:
        _locale: '%allowedLanguages%'

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /{_locale}  
    requirements:
        _locale: '%allowedLanguages%'

