<?php

namespace AdminBundle\Repository;

/**
 * FridgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FridgeRepository extends \Doctrine\ORM\EntityRepository
{
}
